---
title: 'PhysMove: Introduction'
author: "Hannah Calich, Jorge Rodríguez, Víctor Eguíluz & Ana Sequeira"
date: 'Last updated: `r Sys.Date()`'
output:
  officedown::rdocx_document:
    reference_docx: "template.docx"
    plots:
      style: Figure
      align: center
    tables:
      style: Table
vignette: |
  %\VignetteEncoding{UTF-8}  
  %\VignetteIndexEntry{PhysMove: Introduction}  
  %\VignetteEngine{knitr::rmarkdown}
---

<style>
      img {
      border: 0;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 600, 
                      fig.align = 'center', 
                      fig.width = 4, 
                      fig.height = 3,
                      echo = TRUE,
                      collapse = TRUE,
                      fig.path = "images/",
                      comment = "#>") 
```

```{r installation, eval=FALSE}
# Install the devtools package from CRAN (if required)
install.packages("devtools")

# Download the development version from GitHub:
devtools::install_github("HannahCalich/PhysMove", auth_token = "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", build_vignettes = TRUE)
```

```{r load physmove}
# Load PhysMove
library(PhysMove)
```
  
```{r head tracks}
# Preview the first 6 rows of the tracks dataset
head(tracks)
```

```{r tracks head, echo=FALSE, warning=FALSE, message=FALSE} 
library(kableExtra)

head(tracks) %>%
    kable(digits=3, "html", align="l") %>%
    kableExtra::kable_styling(bootstrap_options = c("condensed"), full_width = F, html_font = "Consolas", font_size = 18) %>%  
    kableExtra::column_spec(1, width_min = "100px") %>% 
    kableExtra::column_spec(2:3, width_min = "200px") %>% 
    kableExtra::column_spec(4, width_min = "1685px") %>% 
    kableExtra::row_spec(0:6, background = "#F8F8F8", color = "#60a0b0", extra_css = "padding-top: 0px !important; padding-bottom: 0px !important") %>%
    kableExtra::save_kable("vignettes/word_formatted/tables/tracks_head.png", zoom=1) # html files cant be output to word
```
```{r}
# Determine the structure of the tracks dataset
str(tracks)
```

```{r tracks str, echo=FALSE, warning=FALSE, message=FALSE} 
library(kableExtra)

table <- as.data.frame(capture.output(str(tracks)))
names(table) <- NULL
table <- table[-1,]
row.names(table) <- NULL

table %>%
    kable("html", align="l") %>%
    kableExtra::kable_styling(bootstrap_options = c("condensed"), full_width = F, html_font = "Consolas", font_size = 18) %>%
    kableExtra::column_spec(1, width_min = "2185px") %>%  
    kableExtra::row_spec(1:nrow(table), background = "#F8F8F8", color = "#60a0b0", extra_css = "padding-top: 0px !important; padding-bottom: 0px !important") %>%
    kableExtra::save_kable("vignettes/word_formatted/tables/tracks_str.png", zoom=1) # html files cant be output to word
```
```{r plot_tracks, message=FALSE, fig.width=5, fig.height=3.5}
plotTracks(tracks) 
```
